image: node:18.0.0
definitions:
  steps:
    - step: &install_dependencies
        name: Install Dependencies
        script:
          - yarn install --network-timeout 500000
        caches:
          - node
        artifacts:
          - node_modules/**
    - step: &enforce_code_standards
        name: Enforce Code Standards
        script:
          - yarn lint
          - yarn ts
        caches:
          - node
        artifacts:
          - node_modules/**
    - step: &test_unit
        name: Run Unit Tests
        script:
          - yarn test
        caches:
          - node
        artifacts:
          - node_modules/**
    - step: &build
        size: 2x
        caches:
          - node
        name: Build app
        script:
          - cp .env.beta .env
          - yarn build
        artifacts:
          - dist/**
          - node_modules/**
  default:
    - step: *install_dependencies
    - step: *enforce_code_standards
    - step: *test_unit
  tags:
    release-*:
      - step: *install_dependencies
      - step: *test_unit
      - step: *build
      - step:
          name: Deploy to Firebase
          deployment: staging
          script:
            - pipe: atlassian/firebase-deploy:3.0.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: $FIREBASE_PROJECT


